name: flutter_game_1
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.27.0
  flame_audio: ^2.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/ships/
    - assets/images/explosion/
    - assets/images/items/
    - assets/images/meteor/
    - assets/images/parallax/
    - assets/images/bullets/
    - assets/audio/
